#!/usr/bin/env python3
"""Logic validation for student::histogram (variant 6).

The GPU cannot be executed in this environment, so the exact algorithm used by
the CUDA kernels is reproduced in Python and compared with the CPU reference
from nvidia/include/cpu_reference.hpp:

    counts[abs(int(10.0f * x)) % bins] += 1

The simulation mirrors:
  * histogram_shared_kernel: private per-block histogram, strided init, strided
    accumulation over a grid-stride loop, merge into the global histogram;
  * histogram_global_kernel: direct global accumulation.

It checks the manual example from the gtest suite, boundary sizes, several bin
counts and several block sizes. Only the Python standard library is used.
"""
import random
import sys

BIN_GRID = 0.125  # make_input() uses values on a 0.125 grid


def cpu_histogram(values, bins):
    counts = [0] * bins
    for v in values:
        counts[abs(int(10.0 * v)) % bins] += 1
    return counts


def _bin(x, bins):
    t = int(10.0 * x)  # Python int() truncates toward zero, like C++ static_cast<int>
    return (-t if t < 0 else t) % bins


def gpu_shared_sim(values, bins, block, grid):
    """Simulates histogram_shared_kernel + the global merge (single grid).

    Each block owns a private histogram; every thread of the block walks the
    grid-stride loop independently, exactly as threadIdx.x does on the GPU.
    """
    counts = [0] * bins
    n = len(values)
    stride = grid * block
    for blk in range(grid):
        block_hist = [0] * bins
        # cooperative zeroing: thread tid clears bins tid, tid+block, ...
        for tid in range(block):
            for b in range(tid, bins, block):
                block_hist[b] = 0
        # strided accumulation, one logical thread at a time
        for tid in range(block):
            for i in range(blk * block + tid, n, stride):
                block_hist[_bin(values[i], bins)] += 1
        for b in range(bins):
            counts[b] += block_hist[b]
    return counts


def gpu_global_sim(values, bins, block, grid):
    counts = [0] * bins
    n = len(values)
    stride = grid * block
    for i in range(n):
        counts[_bin(values[i], bins)] += 1
    return counts


def make_values(n, seed=42, pattern="random"):
    rng = random.Random(seed)
    if pattern == "one-bin":
        return [0.0] * n
    return [(rng.randrange(8193) - 4096) * BIN_GRID for _ in range(n)]


def check(label, values, bins, block):
    ref = cpu_histogram(values, bins)
    n = len(values)
    if n == 0:
        grid = 0
    else:
        grid = max(1, min((n + block - 1) // block, 5 * 4))  # cap like occupancy
    got = gpu_shared_sim(values, bins, block, grid) if n else [0] * bins
    got_global = gpu_global_sim(values, bins, block, max(1, grid)) if n else [0] * bins
    assert sum(ref) == n, (label, "reference total", sum(ref), n)
    assert got == ref, (label, "shared mismatch", bins, block)
    assert got_global == ref, (label, "global mismatch", bins, block)
    return ref


def main():
    # Manual example from gtest/test_algorithm.cu.
    example = [0.0, 0.2, 0.1, 0.2]
    got = cpu_histogram(example, 4)
    assert got == [1, 1, 2, 0], got
    print("KnownExample x={0,0.2,0.1,0.2}, bins=4 ->", got, "OK")

    sizes = [0, 1, 2, 31, 32, 33, 63, 64, 65, 127, 128, 129,
             255, 256, 257, 512, 513, 1003, 65537, 1 << 20]
    bin_counts = [1, 2, 4, 16, 256, 257, 4096]
    blocks = [32, 64, 128, 256, 512]
    checks = 0
    for n in sizes:
        for bins in bin_counts:
            for block in blocks:
                values = make_values(n)
                check(f"n={n},bins={bins},B={block}", values, bins, block)
                checks += 1
    # Pattern used by the gtest suite.
    for n in [1003, 65537]:
        for bins in [1, 16, 257]:
            check(f"one-bin n={n},bins={bins}", make_values(n, pattern="one-bin"), bins, 128)
            checks += 1
    # Extreme values: largest magnitude generated by make_input and negatives.
    extremes = [-512.0, -0.05, -0.15, 0.0, 0.05, 0.15, 511.875, 511.999]
    for bins in [1, 3, 16, 256, 257]:
        check(f"extremes bins={bins}", extremes * 7, bins, 128)
        checks += 1
    print(f"{checks} configurations validated against the CPU reference: OK")
    return 0


if __name__ == "__main__":
    sys.exit(main())
